spring:
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${application.data.file}
    username: sa
    password:

application:
  data:
    file: ./fly-high.datastore