CREATE TABLE USER (
  ID          VARCHAR(32)  NOT NULL,
  NAME        VARCHAR(64)  NOT NULL,
  PASSWORD    VARCHAR(32)  NOT NULL,
  ENABLE_FLG      CHAR(1)      NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE FLYWAY (
  ID                  VARCHAR(10)     NOT NULL,
  USER_ID             VARCHAR(32)     NOT NULL,
  NAME                VARCHAR(128)    NOT NULL,
  TYPE                CHAR(2)         NOT NULL,
  URL                 VARCHAR(1024)   NOT NULL,
  USER_NAME           VARCHAR(128),
  PASSWORD            VARCHAR(32),
  MIGRATE_PATH        VARCHAR(1024)   NOT NULL,
  GIT_OAUTH_TOKEN     VARCHAR(128)    NOT NULL,
  GIT_REPOSITORY_URL  VARCHAR(1024) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(USER_ID) REFERENCES USER(ID)
)